#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        export PATH="/Users/travis/Library/Python/3.7/bin:$PATH";
    fi

    export PATH="/Users/runner/Library/Python/3.8/bin:$PATH"
    brew install gnu-sed
    export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
fi

export PATH="$HOME/.local/bin:$PATH"

sed --version
python --version
python3 --version
which python
which python3

echo $PATH


curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --user
python3 -m pip install --user --use-feature=2020-resolver --use-feature=fast-deps  matplotlib jupyter

julia --eval 'using Pkg; pkg"dev https://github.com/Alexander-Barth/GeoMapping.jl"'
julia --project --eval 'using Pkg; Pkg.instantiate();'
julia --project --eval 'using Pkg; Pkg.status();'
jupyter kernelspec list

JULIA_VERSION=$(julia --version | cut --delimiter=' ' --field=3);
JULIA_VERSION_XY=$(echo $JULIA_VERSION | cut  --delimiter='.' --field=1,2);
for i in *.ipynb; do
   echo $i $JULIA_VERSION;
   sed --regexp-extended --in-place "s/julia-1.[0-9]/julia-$JULIA_VERSION_XY/g" "$i";
   sed --regexp-extended --in-place "s/Julia 1.[0-9].[0-9]/Julia $JULIA_VERSION/g" "$i";
   jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=360 "$i";
done
