#!/bin/bash

source "${BASH_SOURCE%/*}/ci-env"

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py --user

python -m pip install matplotlib jupyter

julia --eval 'using Pkg; pkg"dev https://github.com/Alexander-Barth/GeoMapping.jl"'
julia --project --eval 'using Pkg; Pkg.instantiate();'
julia --project --eval 'using Pkg; Pkg.status();'
python -m jupyter kernelspec list

JULIA_VERSION=$(julia --version | cut --delimiter=' ' --field=3);
JULIA_VERSION_XY=$(echo $JULIA_VERSION | cut  --delimiter='.' --field=1,2);

echo JULIA_VERSION $JULIA_VERSION $JULIA_VERSION_XY

for i in *.ipynb; do
   echo $i $JULIA_VERSION;
   sed --regexp-extended --in-place "s/julia-1.[0-9]/julia-$JULIA_VERSION_XY/g" "$i";
   sed --regexp-extended --in-place "s/Julia 1.[0-9].[0-9]/Julia $JULIA_VERSION/g" "$i";
   python -m nbconvert --to html --execute --ExecutePreprocessor.timeout=500 "$i";
done
